### ISSUE TITLE
Task Assignments - Milestone 1

### ISSUE THREAD

**Issue by SimplyTim** [UBC-MDS/wine_quality_predictor_group1#1]
Hey all.

Based on our meeting today, I just wanted to finalize the distribution of work for this week:

- `README.md` - @yixuangaoclara 
- `CODE_OF_CONDUCT.md` - @SimplyTim 
- `CONTRIBUTING.md` - @wzhu8410 
- `data/` - @yixuangaoclara 
- `analysis.ipynb` - All members
- `environment.yml` - @BryanLee06 

For the analysis, the requirements are documented [here](https://pages.github.ubc.ca/MDS-2024-25/DSCI_522_dsci-workflows_students/release/milestone1/milestone1.html#add-the-data-analysis-as-a-literate-code-document).

Just to summarize our discussion today, the flow of this `analysis.ipynb` document will include both the explanation and code for the following steps:

1. Introduction of the topic, dataset, and question
2. Loading of the dataset
3. Data wrangling and/or data cleaning of the dataset (if necessary). 
4. Perform EDA which summarizes the dataset, and create visualizations to capture any potential correlation of the features in the data.
5. Split data into training and testing sets.
6. Create a column transformer that does any necessary preprocessing for the data.
7.  Create pipelines for each of Decision Tree, KNN, SVC and Logistic Regression, including the preprocessors. Perform cross-validation to find the model that performs the best, based on a certain metric (to be discussed).
8. Once a model type is selected, perform hyperparameter optimization to find the best hyperparameters for this model.
9. Run the model on the testing set, and visualize results as necessary.

This is a very high level overview of the tasks. If you believe I forgot or said something incorrectly, just let me know! Also let me know which tasks will be done by whom. For instance, I wouldn't mind doing the coding for parts 6 to 8 from the list above. 

Thanks! 😄

EDIT: I forgot to mention we would have to do separate branches for each task or subset of tasks. So for instance, the EDA might be one branch, the model selection might be another, the hyperparameter optimization might be another, etc.

**Comment by yixuangaoclara** [comment]
For data analysis part:
@yixuangaoclara Introduction, import data, and clean data(step 1 ~ 3). Might do some parts of EDA(step 4) due to data cleaning.
@BryanLee06 Perform EDA, split data and create transformer(step 4 ~ 6).
@SimplyTim Create pipelines for Models and perform cv(step 7).
@wzhu8410 Find the best hyperparameters, run the model on the testing set, and visualize the results(step 8 ~ 9).

**Comment by yixuangaoclara** [comment]
I need to change the summary part of the notebook and the conda lock part of the README file once we finish the other parts.

**Comment by SimplyTim** [comment]
Updated the table titles as well as minor edits to discussion. @BryanLee06 @yixuangaoclara @wzhu8410 any final changes?

**Comment by yixuangaoclara** [comment]
submitted our Milestone 1 PDF on Gradescope

**Comment by SimplyTim** [comment]
Thanks @yixuangaoclara. I'm closing this issue for Milestone 1. Great work guys!
