### ISSUE TITLE
Task Assignments - Milestone 2

### ISSUE THREAD

**Issue by wzhu8410** [UBC-MDS/wine_quality_predictor_group1#10]
Hi team, 

Here are the task assignments for this week's milestone: 

1. Upgrade your project’s computational environment to a container @SimplyTim and @BryanLee06 
2. Add data validation checks to your data analysis @yixuangaoclara and @wzhu8410 

The data validation checks should be placed before the EDA, without looking at the data specifically. 
Clara and Wangkai will double check the Docker environment to make sure that they work as expected. 

Please log new issues or communicate on Slack for questions. Good luck!

**Comment by SimplyTim** [comment]
We started on the Docker section. Our working branch is `docker-image`.

**Comment by BryanLee06** [comment]
Providing link for UCI Dataset website: https://archive.ics.uci.edu/dataset/186/wine+quality

**Comment by SimplyTim** [comment]
Completed Docker image for the our current packages. GitHub Actions is also set up, so every time a change is made and pushed to either the `Dockerfile` or `conda-linux-64.lock` it will automatically be updated to DockerHub. It can be found: https://hub.docker.com/repository/docker/tsingh98/wine_quality_predictor_group1/general

Next, we will create a docker compose file to allow easy access to this container! 😄

**Comment by BryanLee06** [comment]
These are the steps that we did to create the container. 

1. Conda lock file was created for linux 64 bit - using that file we created a docker file that builds our base image which is a Jupyter notebook minimal 
2. After we load the base we import the conda-lock file into docker file
3. The following steps on Github actions we set up a workflow where any time a change is made on our conda-lock file or yml file we pull the changes directly to Docker. This ensure the most updated environment with dependencies is always available.  
4. Docker compose file created, we can pull the entire package and we can use `docker-compose up` in terminal to open an instance of Jupyter lab from the container and run our project. No installs and dependencies will be required.

**Comment by yixuangaoclara** [comment]
I started on the data validation section. The working branch is data_validation.

**Comment by yixuangaoclara** [comment]
I added the data validation check and found duplicates in our dataset, so I removed them. Please let me know if you find other ways to deal with duplicates. Thanks!

**Comment by SimplyTim** [comment]
Thanks, it looks good so far. I just note @wzhu8410's suggestion to add class_weight to the SVC.

Also, were you able to load and access the files using the docker-compose file?

**Comment by SimplyTim** [comment]
Confirmed `docker-compose up` works with @yixuangaoclara.

@wzhu8410 all ready for submission. Thanks everyone.
