### ISSUE TITLE
Milestone 1 Fixes

### ISSUE THREAD

**Issue by wzhu8410** [UBC-MDS/wine_quality_predictor_group1#11]
We should fix the EDA, specifically the order in which we do it.  
EDA should come after train/test split and only be done on the training set. The order would be data validation is done first, data cleaning, train/test split, and EDA.

**Comment by SimplyTim** [comment]
Noted. I created a branch to work on this, and any other fixes that may need to be done.

**Comment by wzhu8410** [comment]
We can delete and tidy up the branches that are already closed. Work will be reflected in the main branch commit history.

**Comment by SimplyTim** [comment]
Sounds good. Can you handle that?

**Comment by wzhu8410** [comment]
> Sounds good. Can you handle that?

Inactive branches are deleted.

**Comment by SimplyTim** [comment]
Thanks. I have reordered the train test split and EDA, as well as took out targets from the EDA.
