### ISSUE TITLE
Milestone 1 fix -  package versions pin in `environment.yml`

### ISSUE THREAD

**Issue by wzhu8410** [UBC-MDS/wine_quality_predictor_group1#12]
Python and package versions are not being pinned in `environment.yml`.  
Python and each and every package in `environment.yml` should have their version pinned using `=`.  Without doing this, you cannot reproducibly create the same environment in the future. How do you get these versions? I recommend activating your environment when you have all your packages installed in it and running `conda list`. You can then look up the versions and pin them in `environment.yml` manually using `=`.

**Comment by SimplyTim** [comment]
Resolved this in #11. Thanks.
