### ISSUE TITLE
Fixes From Feedback From Milestone 1

### ISSUE THREAD

**Issue by wzhu8410** [UBC-MDS/wine_quality_predictor_group1#18]
- CODE_OF_CONDUCT.md: The email under "enforcement" should be tied to the team
- README.md: Summary in README should include high-level interpretation of analysis findings, as well 1-2 sentences on what they might mean (at least at a high-level).
- render PDF for notebook
- LICENSE.md: No Creative Commons license (for project report) was specified.
- Abstract/Summary: Does not discuss importance and limitations of findings.
- Narration of methods and method choices was not as clear and thorough as it could be. You could briefly justify the consideration of selecting each method (e.g. pros and cons, indication etc)
- You team are treating the target as multi-class, ignoring the ordering.
- There are references at the end of the report, but they are not referred to in the narrative.

**Comment by SimplyTim** [comment]
I can make a branch for us to work on for these changes.

I can work on the CODE_OF_CONDUCT.md, rendering to pdf, and maybe the "You team are treating the target as multi-class, ignoring the ordering" issue.

**Comment by wzhu8410** [comment]
Updated LICENSE.md, fixed.

**Comment by yixuangaoclara** [comment]
Updated README summary part and summary part in report
