### ISSUE TITLE
feedback 

### ISSUE THREAD

**Issue by yixuangaoclara** [UBC-MDS/wine_quality_predictor_group1#33]
1. remove unnecessary files such as conda-lock.yml @SimplyTim 
2. update README: file location @yixuangaoclara 
3. add try/except statement to scripts @BryanLee06 @yixuangaoclara @SimplyTim @wzhu8410 
4. save the raw zip file @wzhu8410 
5. add data validation to check correlations @wzhu8410

**Comment by wzhu8410** [comment]
#4 Save raw zip file done

**Comment by yixuangaoclara** [comment]
I updated README file: update analysis process and add final report link

**Comment by yixuangaoclara** [comment]
I added try/except statements to download_data and clean_data scripts
