### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by SimplyTim** [UBC-MDS/wine_quality_predictor_group1#34]
Hi team, great work thus far. Almost there: last milestone.

As discussed, this is the distribution for work:
- Makefile: @SimplyTim @BryanLee06 
- Extract functions from `clean_data.py` and download_data.py with tests for functions. @yixuangaoclara 
- Extract functions from `data_validation.py` and `tuning.py` with tests for functions. @wzhu8410 
- Extract functions from `split_eda.py` with tests for functions. @BryanLee06 
- Extract functions from `model_selection.py` and `model_evaluation.py` with tests for functions. @SimplyTim

**Comment by SimplyTim** [comment]
Note @wzhu8410 for the data validation script, it is fine to get ride of the entire script and abstract it to a function. This function can simply be called at the beginning of `split_eda.py` or at the end of `clean_data.py`

**Comment by yixuangaoclara** [comment]
1. FEEDBACK

- make changes based on feedback
- create a CHANGELOG.md file in the root of the repository
- provide URLs as evidences with some narration

2. SRC

- create functions from scripts
- import functions in scripts

3. Test

- create tests

**Comment by SimplyTim** [comment]
Updates done:
1) Created `cross_val_score`, `confusion_matrix_multi` and `summarize_conf_matrix` functions.
2) Creates tests for these scripts that can be run with `pytest`

**Comment by BryanLee06** [comment]
1. Updated fixes required on the changelog 
2. created functions and tests for train_test_split and EDA charst
3. Made updates based on feedback received from peer review.

**Comment by BryanLee06** [comment]
Submitted!
